/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "k8s.io/api/scopes/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	scopesv1alpha1 "k8s.io/client-go/applyconfigurations/scopes/v1alpha1"
	gentype "k8s.io/client-go/gentype"
	scheme "k8s.io/client-go/kubernetes/scheme"
)

// ScopesGetter has a method to return a ScopeInterface.
// A group's client should implement this interface.
type ScopesGetter interface {
	Scopes() ScopeInterface
}

// ScopeInterface has methods to work with Scope resources.
type ScopeInterface interface {
	Create(ctx context.Context, scope *v1alpha1.Scope, opts v1.CreateOptions) (*v1alpha1.Scope, error)
	Update(ctx context.Context, scope *v1alpha1.Scope, opts v1.UpdateOptions) (*v1alpha1.Scope, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, scope *v1alpha1.Scope, opts v1.UpdateOptions) (*v1alpha1.Scope, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Scope, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ScopeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Scope, err error)
	Apply(ctx context.Context, scope *scopesv1alpha1.ScopeApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Scope, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, scope *scopesv1alpha1.ScopeApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Scope, err error)
	ScopeExpansion
}

// scopes implements ScopeInterface
type scopes struct {
	*gentype.ClientWithListAndApply[*v1alpha1.Scope, *v1alpha1.ScopeList, *scopesv1alpha1.ScopeApplyConfiguration]
}

// newScopes returns a Scopes
func newScopes(c *ScopesV1alpha1Client) *scopes {
	return &scopes{
		gentype.NewClientWithListAndApply[*v1alpha1.Scope, *v1alpha1.ScopeList, *scopesv1alpha1.ScopeApplyConfiguration](
			"scopes",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.Scope { return &v1alpha1.Scope{} },
			func() *v1alpha1.ScopeList { return &v1alpha1.ScopeList{} }),
	}
}
