/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-codegen.sh

// AUTO-GENERATED FUNCTIONS START HERE. DO NOT EDIT.
var map_ScopeDefinition = map[string]string{
	"":         "ScopeDefinition is a definition of a mapping between a scope (name, value) tuple and a list of namespace names. The metadata.namespace field is used to represent the scope name, and the metadata.name field is used to represent the scope value. For example, a ScopeDefinition in the namespace 'workspace' with name 'my-workspace' would correspond to the scope selector `scope.k8s.io/workspace=my-workspace`. A scopes generation field is used to uniquely identify a revision of a scope configuration.",
	"metadata": "Standard object's metadata.",
}

func (ScopeDefinition) SwaggerDoc() map[string]string {
	return map_ScopeDefinition
}

var map_ScopeDefinitionList = map[string]string{
	"":         "ScopeDefinitionList is a collection of ScopeDefinition objects.",
	"metadata": "Standard object's metadata.",
}

func (ScopeDefinitionList) SwaggerDoc() map[string]string {
	return map_ScopeDefinitionList
}

var map_ScopeDefinitionSpec = map[string]string{
	"namespaces": "Namespaces is the list of namespaces currently contained within this scope.",
}

func (ScopeDefinitionSpec) SwaggerDoc() map[string]string {
	return map_ScopeDefinitionSpec
}

// AUTO-GENERATED FUNCTIONS END HERE
